# Generated by Django 3.0.4 on 2020-09-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeyFoodie', '0006_order_detail_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesize',
            name='menu',
        ),
        migrations.AddField(
            model_name='menu',
            name='salesize',
            field=models.ManyToManyField(to='HeyFoodie.SaleSize'),
        ),
    ]
