# Generated by Django 3.0.4 on 2020-10-18 14:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HeyFoodie', '0007_auto_20200926_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='close_order',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='open_order',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CREDIT', 'Credit/Debit')], default='CASH', max_length=20),
        ),
    ]
