# Generated by Django 3.0.4 on 2020-10-26 13:30

from django.db import migrations, models
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('HeyFoodie', '0008_auto_20201018_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='fbpage',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='igac',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='lineac',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='open_day',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'จันทร์'), (2, 'อังคาร'), (3, 'พุธ'), (4, 'พฤหัสบดี'), (5, 'ศุกร์'), (6, 'เสาร์'), (7, 'อาทิตย์')], max_length=20),
        ),
    ]
