# Generated by Django 3.0.4 on 2020-11-12 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeyFoodie', '0009_auto_20201026_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='price',
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
