# Generated by Django 3.0.4 on 2020-11-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeyFoodie', '0012_auto_20201113_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='email',
            field=models.CharField(default='heypizza@gmail.com', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='phone',
            field=models.CharField(default='0800000000', max_length=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
