# Generated by Django 3.0.4 on 2020-11-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeyFoodie', '0013_auto_20201114_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='purchase_date',
            field=models.DateTimeField(null=True),
        ),
    ]
