# Generated by Django 3.0.4 on 2020-11-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeyFoodie', '0016_auto_20201115_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('complete', 'Complete'), ('waiting', 'Waiting'), ('cancel', 'Cancel')], default='waiting', max_length=20),
        ),
    ]
