# Generated by Django 3.0.4 on 2020-11-20 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HeyFoodie', '0018_auto_20201116_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bestsellmenu_month',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='bestsellmenu_month',
            name='report_month',
        ),
        migrations.DeleteModel(
            name='Bestsellmenu_Day',
        ),
        migrations.DeleteModel(
            name='Bestsellmenu_Month',
        ),
        migrations.DeleteModel(
            name='Report_Day',
        ),
        migrations.DeleteModel(
            name='Report_Month',
        ),
    ]
