# Generated by Django 3.0.4 on 2020-11-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeyFoodie', '0020_remove_order_detail_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='fbpage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='igac',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='lineac',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
